<script setup lang="ts">
import { onMounted, reactive, ref, watch } from 'vue'
import { Database, Download, Eye, LoaderCircle, Play, Plus, RefreshCw, Trash2, X } from 'lucide-vue-next'
import { api, downloadFile, type DataConnection, type ExtractJob, type Project } from '../api/client'
import FilePreview from '../components/FilePreview.vue'
const props = defineProps<{ project: Project | null }>(); const connections = ref<DataConnection[]>([]); const jobs = ref<ExtractJob[]>([]); const showConnection = ref(false); const busy = ref(false); const message = ref('')
const connection = reactive({ name: '', sourceType: 'POSTGRESQL', jdbcUrl: 'jdbc:postgresql://localhost:5432/database', username: '', secretRef: '' })
const extract = reactive({ connectionId: '', name: '', sql: 'select * from your_table', outputName: 'data.csv', fetchSize: 5000 })
const previewing = ref<ExtractJob | null>(null)
async function load() { if (!props.project) return; [connections.value, jobs.value] = await Promise.all([api.listConnections(props.project.id), api.listExtracts(props.project.id)]); if (!extract.connectionId && connections.value[0]) extract.connectionId = connections.value[0].id }
async function createConnection() { if (!props.project) return; busy.value = true; message.value = ''; try { await api.createConnection({ projectId: props.project.id, ...connection, options: {} }); showConnection.value = false; await load() } catch (e) { message.value = e instanceof Error ? e.message : '连接没有保存' } finally { busy.value = false } }
async function test(item: DataConnection) { message.value = '正在检查连接…'; try { const result = await api.testConnection(item.id); message.value = `${result.databaseProduct} ${result.databaseVersion}，连接正常（${result.latencyMs} ms）`; await load() } catch (e) { message.value = e instanceof Error ? e.message : '连接检查失败' } }
async function runExtract() { if (!props.project) return; busy.value = true; const selected = connections.value.find(item => item.id === extract.connectionId); const sql = selected?.sourceType === 'HTTP_API' ? 'GET' : extract.sql; try { await api.createExtract({ projectId: props.project.id, ...extract, sql }); message.value = '抽取任务已开始，可离开本页继续工作'; await load() } catch (e) { message.value = e instanceof Error ? e.message : '抽取没有开始' } finally { busy.value = false } }
async function deleteConnection(item: DataConnection) { if (!window.confirm(`删除数据连接“${item.name}”？`)) return; try { await api.deleteConnection(item.id); await load(); message.value = '数据连接已删除' } catch (e) { message.value = e instanceof Error ? e.message : '数据连接没有删除' } }
async function deleteJob(item: ExtractJob) { if (!window.confirm(`删除数据“${item.outputName}”？CSV 文件也会一起删除。`)) return; try { await api.deleteExtract(item.id); if (previewing.value?.id === item.id) previewing.value = null; await load(); message.value = 'CSV 数据已删除' } catch (e) { message.value = e instanceof Error ? e.message : '数据没有删除' } }
async function download(item: ExtractJob) { try { await downloadFile('extract-jobs', item.id, item.outputName) } catch (e) { message.value = e instanceof Error ? e.message : '下载失败' } }
watch(() => props.project?.id, load); onMounted(load)
</script>
<template><main class="workspace"><header class="page-header"><div><p class="eyebrow">数据</p><h1>连接并抽取数据</h1><p>从数据库按批读取，直接写入 CSV，不把千万行数据一次装进内存。</p></div><button class="primary-button" type="button" @click="showConnection = !showConnection"><X v-if="showConnection" :size="17"/><Plus v-else :size="17"/>{{ showConnection ? '收起' : '添加连接' }}</button></header>
  <p v-if="message" class="notice">{{ message }}</p>
  <section v-if="showConnection" class="form-band"><h2>添加数据连接</h2><div class="form-grid"><label><span>连接名称</span><input v-model="connection.name" placeholder="例如：经营数据仓库"></label><label><span>数据类型</span><select v-model="connection.sourceType"><option value="POSTGRESQL">PostgreSQL</option><option value="MYSQL">MySQL</option><option value="OPENGAUSS">openGauss</option><option value="GAUSS_DWS">GaussDB(DWS)</option><option value="DUCKDB">DuckDB</option><option value="HTTP_API">HTTP 数据服务</option></select></label><label class="wide"><span>连接地址</span><input v-model="connection.jdbcUrl"></label><label><span>用户名</span><input v-model="connection.username"></label><label><span>密码环境变量</span><input v-model="connection.secretRef" placeholder="env:FINFLOW_DB_PASSWORD"></label></div><button class="primary-button" :disabled="busy" type="button" @click="createConnection">保存连接</button></section>
  <div class="two-column"><section class="content-band"><div class="section-title-row"><div><span>已保存</span><h2>数据连接</h2></div><button class="icon-button" title="刷新" @click="load"><RefreshCw :size="17"/></button></div><div v-if="!connections.length" class="empty-state compact"><Database :size="25"/><strong>还没有数据连接</strong></div><div class="resource-list"><div v-for="item in connections" :key="item.id" class="resource-row"><span class="resource-icon"><Database :size="18"/></span><button class="connection-main" type="button" @click="test(item)"><strong>{{ item.name }}</strong><small>{{ item.sourceType }} · {{ item.status || '尚未检查' }}</small></button><div class="row-actions"><button class="secondary-button" type="button" @click="test(item)">检查</button><button class="icon-button danger" type="button" title="删除连接" @click="deleteConnection(item)"><Trash2 :size="16"/></button></div></div></div></section>
  <section class="form-band"><h2>抽取为 CSV</h2><div class="form-stack"><label><span>数据连接</span><select v-model="extract.connectionId"><option value="" disabled>请选择</option><option v-for="item in connections" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label><span>任务名称</span><input v-model="extract.name" placeholder="例如：8 月经营明细"></label><label><span>只读查询</span><textarea v-model="extract.sql" rows="5"></textarea></label><label><span>文件名</span><input v-model="extract.outputName"></label></div><button class="primary-button" :disabled="busy || !extract.connectionId" type="button" @click="runExtract"><Play :size="16"/>开始抽取</button></section></div>
  <section class="content-band"><div class="section-title-row"><div><span>任务记录</span><h2>CSV 抽取</h2></div></div><div v-if="!jobs.length" class="empty-state compact"><strong>还没有抽取任务</strong></div><div class="table-wrap"><table v-if="jobs.length"><thead><tr><th>任务</th><th>状态</th><th>行数</th><th>文件大小</th><th></th></tr></thead><tbody><tr v-for="job in jobs" :key="job.id"><td><strong>{{ job.name }}</strong><small>{{ job.outputName }}</small></td><td><span class="status" :data-status="job.status"><LoaderCircle v-if="job.status === 'RUNNING'" :size="14"/>{{ job.status }}</span></td><td>{{ job.rowCount.toLocaleString() }}</td><td>{{ (job.byteCount / 1048576).toFixed(1) }} MB</td><td><div class="row-actions"><button v-if="job.status === 'SUCCEEDED'" class="icon-button" type="button" title="在线查看" @click="previewing = job"><Eye :size="17"/></button><button v-if="job.status === 'SUCCEEDED'" class="icon-button" type="button" title="下载" @click="download(job)"><Download :size="17"/></button><button class="icon-button danger" type="button" title="删除数据" @click="deleteJob(job)"><Trash2 :size="16"/></button></div></td></tr></tbody></table></div></section>
  <FilePreview v-if="previewing" :source="{ kind: 'extract-jobs', id: previewing.id, name: previewing.outputName, format: 'csv' }" @close="previewing = null"/>
</main></template>
