<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Download, Eye, FileOutput, Plus, Search } from 'lucide-vue-next'
import { api, downloadFile, type ArtifactQuality, type Deliverable, type KnowledgeRef, type PptSkill, type Project } from '../api/client'
import FilePreview from '../components/FilePreview.vue'
const props = defineProps<{ project: Project | null }>(); const outputs = ref<Deliverable[]>([]); const refs = ref<KnowledgeRef[]>([]); const pptSkills = ref<PptSkill[]>([]); const query = ref(''); const busy = ref(false); const message = ref('')
const form = reactive({ generationPrompt: '', format: 'pptx', pptSkill: 'guizang-huawei-style-c', refIds: [] as string[] })
const presentationSkills = computed(() => pptSkills.value.filter(skill => skill.formats.includes(form.format)))
const previewing = ref<Deliverable | null>(null)
const qualities = ref<Record<string, ArtifactQuality>>({})
async function load() { if (props.project) { const [loadedOutputs, loadedSkills] = await Promise.all([api.listDeliverables(props.project.id), api.listPptSkills()]); outputs.value = loadedOutputs; pptSkills.value = loadedSkills; const entries = await Promise.all(loadedOutputs.map(async item => [item.id, await api.getDeliverableQuality(item.id).catch(() => ({}))] as const)); qualities.value = Object.fromEntries(entries) } }
async function search() { if (props.project && query.value.trim()) refs.value = await api.searchRefs(props.project.id, query.value) }
function inferredTitle() { const clean = form.generationPrompt.trim().replace(/^(?:请帮我|帮我|请|生成|制作|创建|输出)\s*/u, ''); return (clean.split(/[。！？\n]/u)[0] || '智能生成成果').slice(0, 80) }
async function create() { if (!props.project) return; busy.value = true; try { await api.createDeliverable({ projectId: props.project.id, title: inferredTitle(), subtitle: '', format: form.format, pptSkill: ['pptx', 'html_slides'].includes(form.format) ? form.pptSkill : '', includeCitations: form.refIds.length > 0, citationStyle: 'IEEE', sections: [{ heading: '生成要求', paragraphs: [form.generationPrompt.trim()], bullets: [], refIds: form.refIds, citations: [] }] }); message.value = '输出文件已经生成并完成质量检查'; await load() } catch (e) { message.value = e instanceof Error ? e.message : '输出生成失败' } finally { busy.value = false } }
async function download(item: Deliverable) { try { await downloadFile('deliverables', item.id, item.name) } catch (e) { message.value = e instanceof Error ? e.message : '下载失败' } }
function place(item: KnowledgeRef) { return Object.values(item.location).join(' · ') }
watch(() => props.project?.id, load); watch(() => form.format, value => { form.pptSkill = value === 'html_slides' ? 'frontend-slides' : value === 'pptx' ? 'guizang-huawei-style-c' : '' }); onMounted(load)
</script>
<template><main class="workspace"><header class="page-header"><div><p class="eyebrow">输出</p><h1>生成可交付文件</h1><p>说明你需要什么结果，系统会自行组织标题、结构、篇幅和版式，并检查真实文件。</p></div></header><p v-if="message" class="notice">{{ message }}</p>
  <div class="two-column output-layout"><section class="form-band"><h2>新建输出</h2><div class="form-stack"><label><span>格式</span><select v-model="form.format"><option value="pptx">PowerPoint</option><option value="html_slides">网页演示</option><option value="docx">Word</option><option value="pdf">PDF</option><option value="mermaid">Mermaid 图表</option><option value="excalidraw">Excalidraw 白板</option></select></label><p v-if="form.format === 'html_slides'" class="field-help">生成可直接在浏览器中演示的网页文件。</p><label v-if="['pptx','html_slides'].includes(form.format)"><span>演示风格</span><select v-model="form.pptSkill"><option v-if="form.format === 'pptx'" value="">FinBTP Studio 简约蓝白</option><option v-for="skill in presentationSkills" :key="skill.id" :value="skill.id">{{ skill.name }} · {{ skill.theme }}</option></select></label><label><span>生成要求</span><textarea v-model="form.generationPrompt" rows="8" placeholder="例如：根据选中的资料生成一份面向管理层的经营分析，说明关键变化、原因、风险和下一步行动。"></textarea></label></div><div class="ref-picker"><label><span>使用资料</span><div class="inline-search"><input v-model="query" placeholder="搜索已验证资料" @keydown.enter="search"><button class="icon-button" @click="search"><Search :size="17"/></button></div></label><label v-for="item in refs" :key="item.id" class="ref-option"><input v-model="form.refIds" type="checkbox" :value="item.id"><span><strong>{{ item.sourceName }}</strong><small>{{ place(item) }} · {{ item.text.slice(0, 60) }}</small></span></label></div><button class="primary-button" :disabled="busy || !form.generationPrompt.trim()" @click="create"><Plus :size="16"/>{{ busy ? '正在生成并检查…' : '生成文件' }}</button></section>
  <section class="content-band"><div class="section-title-row"><div><span>已生成</span><h2>输出文件</h2></div></div><div v-if="!outputs.length" class="empty-state"><FileOutput :size="28"/><strong>还没有输出</strong><p>填写左侧内容后生成第一份文件。</p></div><div class="resource-list"><div v-for="item in outputs" :key="item.id" class="resource-row"><span class="resource-icon"><FileOutput :size="18"/></span><span><strong>{{ item.name }}</strong><small>{{ item.format.toUpperCase() }} · 第 {{ item.currentVersion }} 版 · {{ (item.sizeBytes / 1024).toFixed(0) }} KB<span v-if="qualities[item.id]?.score"> · 质量检查 {{ qualities[item.id].score }} 分</span></small></span><div class="row-actions"><button class="icon-button" type="button" title="在线查看" @click="previewing = item"><Eye :size="17"/></button><button class="icon-button" type="button" title="下载" @click="download(item)"><Download :size="17"/></button></div></div></div></section></div>
  <FilePreview v-if="previewing" :source="{ kind: 'deliverables', id: previewing.id, name: previewing.name, format: previewing.format }" @close="previewing = null"/>
</main></template>
