<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Download, Eye, FileOutput, Plus, Search } from 'lucide-vue-next'
import { api, downloadUrl, type Deliverable, type KnowledgeRef, type PptSkill, type Project } from '../api/client'
import FilePreview from '../components/FilePreview.vue'
const props = defineProps<{ project: Project | null }>(); const outputs = ref<Deliverable[]>([]); const refs = ref<KnowledgeRef[]>([]); const pptSkills = ref<PptSkill[]>([]); const query = ref(''); const busy = ref(false); const message = ref('')
const form = reactive({ title: '', subtitle: '', format: 'pptx', pptSkill: 'guizang-huawei-style-c', heading: '核心结论', paragraphs: '', bullets: '', refIds: [] as string[] })
const presentationSkills = computed(() => pptSkills.value.filter(skill => skill.formats.includes(form.format)))
const previewing = ref<Deliverable | null>(null)
async function load() { if (props.project) { const [loadedOutputs, loadedSkills] = await Promise.all([api.listDeliverables(props.project.id), api.listPptSkills()]); outputs.value = loadedOutputs; pptSkills.value = loadedSkills } }
async function search() { if (props.project && query.value.trim()) refs.value = await api.searchRefs(props.project.id, query.value) }
async function create() { if (!props.project) return; busy.value = true; try { await api.createDeliverable({ projectId: props.project.id, title: form.title, subtitle: form.subtitle, format: form.format, pptSkill: ['pptx', 'html_slides'].includes(form.format) ? form.pptSkill : '', sections: [{ heading: form.heading, paragraphs: form.paragraphs.split('\n').filter(Boolean), bullets: form.bullets.split('\n').filter(Boolean), refIds: form.refIds, citations: [] }] }); message.value = '输出文件已经生成'; await load() } catch (e) { message.value = e instanceof Error ? e.message : '输出生成失败' } finally { busy.value = false } }
function place(item: KnowledgeRef) { return Object.values(item.location).join(' · ') }
watch(() => props.project?.id, load); watch(() => form.format, value => { form.pptSkill = value === 'html_slides' ? 'frontend-slides' : value === 'pptx' ? 'guizang-huawei-style-c' : '' }); onMounted(load)
</script>
<template><main class="workspace"><header class="page-header"><div><p class="eyebrow">输出</p><h1>生成可交付文件</h1><p>把分析内容和 Ref 生成 PPT、Word 或 Mermaid，来源会随文件一起保留。</p></div></header><p v-if="message" class="notice">{{ message }}</p>
  <div class="two-column output-layout"><section class="form-band"><h2>新建输出</h2><div class="form-stack"><label><span>标题</span><input v-model="form.title" placeholder="8 月经营复盘"></label><label><span>副标题</span><input v-model="form.subtitle" placeholder="经营表现与后续行动"></label><label><span>格式</span><select v-model="form.format"><option value="pptx">PowerPoint</option><option value="html_slides">网页演示（HTML + JS，非 PPT）</option><option value="docx">Word</option><option value="mermaid">Mermaid 图表</option></select></label><p v-if="form.format === 'html_slides'" class="field-help">生成的是浏览器演示文件，不是 PowerPoint，不能使用 PowerPoint 或 OnlyOffice 原生编辑。</p><label v-if="['pptx','html_slides'].includes(form.format)"><span>演示风格技能</span><select v-model="form.pptSkill"><option v-if="form.format === 'pptx'" value="">FinFlow 简约蓝白</option><option v-for="skill in presentationSkills" :key="skill.id" :value="skill.id">{{ skill.name }} · {{ skill.theme }}</option></select></label><label><span>章节标题</span><input v-model="form.heading"></label><label><span>正文（每行一段）</span><textarea v-model="form.paragraphs" rows="4"></textarea></label><label><span>要点（每行一条）</span><textarea v-model="form.bullets" rows="4"></textarea></label></div><div class="ref-picker"><label><span>添加 Ref</span><div class="inline-search"><input v-model="query" placeholder="搜索资料" @keydown.enter="search"><button class="icon-button" @click="search"><Search :size="17"/></button></div></label><label v-for="item in refs" :key="item.id" class="ref-option"><input v-model="form.refIds" type="checkbox" :value="item.id"><span><strong>{{ item.sourceName }}</strong><small>{{ place(item) }} · {{ item.text.slice(0, 60) }}</small></span></label></div><button class="primary-button" :disabled="busy || !form.title" @click="create"><Plus :size="16"/>{{ busy ? '正在生成…' : '生成文件' }}</button></section>
  <section class="content-band"><div class="section-title-row"><div><span>已生成</span><h2>输出文件</h2></div></div><div v-if="!outputs.length" class="empty-state"><FileOutput :size="28"/><strong>还没有输出</strong><p>填写左侧内容后生成第一份文件。</p></div><div class="resource-list"><div v-for="item in outputs" :key="item.id" class="resource-row"><span class="resource-icon"><FileOutput :size="18"/></span><span><strong>{{ item.name }}</strong><small>{{ item.format.toUpperCase() }} · 第 {{ item.currentVersion }} 版 · {{ (item.sizeBytes / 1024).toFixed(0) }} KB</small></span><div class="row-actions"><button class="icon-button" type="button" title="在线查看" @click="previewing = item"><Eye :size="17"/></button><a class="icon-button" :href="downloadUrl('deliverables', item.id)" title="下载"><Download :size="17"/></a></div></div></div></section></div>
  <FilePreview v-if="previewing" :source="{ kind: 'deliverables', id: previewing.id, name: previewing.name, format: previewing.format }" @close="previewing = null"/>
</main></template>
