<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { Download, FileUp, RefreshCw, Sheet } from 'lucide-vue-next'
import { api, downloadUrl, type FileResource, type Project, type SpreadsheetProfile } from '../api/client'
const props = defineProps<{ project: Project | null }>(); const files = ref<FileResource[]>([]); const selected = ref(''); const profile = ref<SpreadsheetProfile | null>(null); const busy = ref(false); const message = ref('')
const sheets = computed(() => files.value.filter(f => /\.(xlsx|xlsm|csv|tsv)$/i.test(f.name))); const form = reactive({ oldHeader: '', newHeader: '', fillHeader: '', fillValue: '', formulaName: '', formula: '', removeDuplicates: false })
async function load() { if (!props.project) return; files.value = await api.listFiles(props.project.id); if (!selected.value && sheets.value[0]) selected.value = sheets.value[0].id }
async function upload(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (!file || !props.project) return; busy.value = true; try { const item = await api.uploadFile(props.project.id, file); selected.value = item.id; await load(); await inspect() } catch (e) { message.value = e instanceof Error ? e.message : '上传失败' } finally { busy.value = false; input.value = '' } }
async function inspect() { if (!selected.value) return; busy.value = true; try { profile.value = await api.profileSpreadsheet(selected.value) } catch (e) { message.value = e instanceof Error ? e.message : '无法读取表格概况' } finally { busy.value = false } }
async function transform() { if (!selected.value) return; busy.value = true; const renameHeaders = form.oldHeader && form.newHeader ? { [form.oldHeader]: form.newHeader } : {}; const fillBlanks = form.fillHeader ? { [form.fillHeader]: form.fillValue } : {}; const formulaColumns = form.formulaName && form.formula ? [{ name: form.formulaName, formula: form.formula }] : []; try { await api.transformSpreadsheet(selected.value, { renameHeaders, fillBlanks, formulaColumns, removeDuplicates: form.removeDuplicates }); message.value = '已生成新版本，原表格仍然保留'; await load(); await inspect() } catch (e) { message.value = e instanceof Error ? e.message : '表格加工失败' } finally { busy.value = false } }
watch(() => props.project?.id, load); onMounted(load)
</script>
<template><main class="workspace"><header class="page-header"><div><p class="eyebrow">表格</p><h1>检查与加工表格</h1><p>保留原文件，每次加工生成新版本；支持公式概况和 `.xlsm` 宏保留。</p></div><label class="primary-button upload-button"><FileUp :size="17"/>上传表格<input type="file" accept=".xlsx,.xlsm,.csv,.tsv" @change="upload"></label></header><p v-if="message" class="notice">{{ message }}</p>
  <div class="two-column"><section class="content-band"><div class="section-title-row"><div><span>表格文件</span><h2>选择表格</h2></div></div><select v-model="selected" class="full-select" @change="profile = null"><option value="" disabled>请选择</option><option v-for="file in sheets" :key="file.id" :value="file.id">{{ file.name }}（第 {{ file.currentVersion }} 版）</option></select><button class="secondary-button action-gap" :disabled="!selected || busy" @click="inspect"><RefreshCw :size="16"/>读取概况</button><a v-if="selected" class="text-link" :href="downloadUrl('files', selected)"><Download :size="16"/>下载当前版本</a><div v-if="profile" class="profile-list"><div><span>格式</span><strong>{{ profile.format.toUpperCase() }}</strong></div><div><span>宏</span><strong>{{ profile.has_macros ? '已检测并保留' : '无' }}</strong></div><div v-for="sheet in profile.sheets" :key="sheet.name"><span>{{ sheet.name }}</span><strong>{{ sheet.rows.toLocaleString() }} 行 · {{ sheet.columns }} 列 · {{ sheet.formula_count }} 个公式</strong></div><p v-for="warning in profile.warnings" :key="warning">{{ warning }}</p></div><div v-if="!sheets.length" class="empty-state compact"><Sheet :size="26"/><strong>还没有表格</strong></div></section>
  <section class="form-band"><h2>生成加工版本</h2><div class="form-stack"><div class="split-fields"><label><span>原列名</span><input v-model="form.oldHeader" placeholder="收入"></label><label><span>新列名</span><input v-model="form.newHeader" placeholder="营业收入"></label></div><div class="split-fields"><label><span>填空列</span><input v-model="form.fillHeader" placeholder="区域"></label><label><span>填充值</span><input v-model="form.fillValue" placeholder="未填写"></label></div><label><span>新增公式列名</span><input v-model="form.formulaName" placeholder="利润"></label><label><span>公式</span><input v-model="form.formula" placeholder="=A{row}-B{row}"></label><label class="check-row"><input v-model="form.removeDuplicates" type="checkbox"><span>删除完全重复的行</span></label></div><button class="primary-button" :disabled="!selected || busy" @click="transform">{{ busy ? '正在处理…' : '生成新版本' }}</button></section></div>
</main></template>
